version: '2'

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - /srv/docker/opencon2018/postgres_data_dev:/var/lib/postgresql/data
      - /srv/docker/opencon2018/postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=opencon2018

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - POSTGRES_USER=opencon2018
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "9122:9122"
    links:
      - postgres
